Progress events without breaking pub-sub
ipfs/js-ipfs-utils pull request #60
Opened 2020-08-18 00:21 UTC by Gozala

This is second take on #52, which end up breaking pubsub. It is based on #57 which fixed another issue.

With this changes `fetch` will use XHR if either `options.onDownloadProgress` or `options.onUploadProgress` is provided. Otherwise it will stick to native `fetch`. This way `file.add` could opt-in into observing progress, but have all of response be buffered before ability to consume it. Pubsub on the other hand doesn't really care about progress events and therefor will continue using `fetch` that can have a streaming response body.

2020-08-18 00:36 UTC, Gozala commented
Electron seems to be failing because we use native fetch there, while we're passing non native `AbortController`. Prior to #54 we used `node-fetch` in electron so this issue did not came up. Then #54 just switched to XHR (using native APIs in Electron). And now that we're going for hybrid approach it became a problem, because native `fetch` in electron expects native `AbortSignal` instead of custom implementation from [abort-controller](https://npmjs.com/package/abort-controller)

I think proper solution would be to make `abort-controller` use native one in electron (or wherever it's available really). But I think we might need a shortcut here.

2020-08-18 01:18 UTC, Gozala commented
Now this got complicated. It looks like http module makes use of [any-singnal](https://github.com/jacobheun/any-signal) which in turn uses `abort-controller`. So even if native `AbortSignal` is passed it will be turned into non native. Switching any-signal to use `AbortController` from `ipfs-utils` would have been an option, but that would introduce circular dependency 😖

Not sure what's the best thing to do here is. I have created https://github.com/mysticatea/abort-controller/issues/24

2020-08-18 11:40 UTC, hugomrdias commented
I would really like to avoid #52 #54 #57 and this one by doing nothing or at best implement download progress (which can be done using fetch). 
This is getting too complex and will only increase maintenance #54 is already and example of that. 

Upload progress is and always was a dream thats why browsers never implemented it (or streams) any box between client and origin server can buffer the request and the progress means nothing. Hopefully in the future this will change (chrome is already implementing streams but warns about this problem).

Sorry for not supporting this, lots of good work went into making this, but i really think its best not to increase complexity for the upload progress.

This is just my opinion if others support this i will not block it.

2020-08-18 19:25 UTC, Gozala commented
> Upload progress is and always was a dream thats why browsers never implemented it (or streams) any box between client and origin server can buffer the request and the progress means nothing. Hopefully in the future this will change (chrome is already implementing streams but warns about this problem).

The main motivation here is to support upload progress in webui. Adding a large file takes a long enough that webui appears broken. E.g. 2gig file takes 10-12secs (for more details and numbers see https://github.com/ipfs-shipyard/ipfs-webui/pull/1534)

With this changes it was possible to render fairly accurate progrssbar. Your comment about box between server and client is correct, but it does not apply to the problem we were trying to solve, because webui talks to the local node.

I personally do not think that waiting on chrome to ship request streams, then waiting for it to propagate to the electron and giving up on non-chromium browsers in order to reduced complexity is the right tradeoff, because it leaves wrong impression  of the IPFS ecosystem when someone is just trying to add a file.

However there might be alternative ways we could consider to provide a feedback, e.g. infinite spinners. They do help a bit, but don't really work for long tasks that take 10secs.

2020-08-20 15:09 UTC, jacobheun commented
I think the UX improvement this adds outweighs the additional complexity. We should add some additional tests here to catch regressions. @Gozala can we add some tests to validate this actually fixes the streaming issue we had with pubsub? 

While I did run this branch against js-ipfs previously and the tests passed, we shouldn't need to rely on that suite to verify things are working as expected.

2020-08-20 15:13 UTC, lidel commented
> I personally do not think that waiting on chrome to ship request streams, then waiting for it to propagate to the electron and giving up on non-chromium browsers in order to reduced complexity is the right tradeoff, because it leaves wrong impression of the IPFS ecosystem when someone is just trying to add a file.

+1 on this.  I believe that shifting burden from the library to its  user is a bad trade off here:

We document `progress` handler at [`js-ipfs/docs/core-api/`](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#options) and it is a terrible devexp when it really does not work over HTTP API. 

Bunch of developers try to implement progress reporting, hit this problem, and waste bunch of time debugging because our docs say `progress` should work, but it does not really work.

Even if our docs were honest and admit it does not work over HTTP API, people have the same problem we have in webui right now, and will waste time on implementing alternative UX strategies to indicate "fake progress". 

Sad reality is that nobody will care or appreciate that we "wait 2 or 5 more years for browsers to fix this mess",
devs new to the ecosystem will blame IPFS for either dishonest/outdated docs or `ipfs.add` missing "the most basic functionality".

2020-08-24 10:44 UTC, achingbrain commented
This is the wrong solution as it ignores what's actually going during the API call (e.g. the HTTP request and the API request may have different notions of 'progress'), but sadly the right solution is completely impractical right now (bidirectional HTTP streaming in browsers) so it'll have to do.

Can you also please:

1. Open a PR against js-ipfs with this branch as the `ipfs-utils` dep version to make sure the tests pass with these changes
1. Expose and document the new upload/download progress args in ipfs-http-client
    - These probably just need documenting under [additional options](https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-http-client#additional-options) in the ipfs-http-client README, not the core-api docs as they make no sense in the context of calling into core/running a full IPFS node in the browser or node.js
1. Ensure it doesn't cause a regression for https://github.com/ipfs/js-ipfs/issues/3238

2020-10-02 06:50 UTC, Gozala commented
>   1. Open a PR against js-ipfs with this branch as the `ipfs-utils` dep version to make sure the tests pass with these changes

https://github.com/ipfs/js-ipfs/pull/3310

> 2. Expose and document the new upload/download progress args in ipfs-http-client
> 
>     * These probably just need documenting under [additional options](https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-http-client#additional-options) in the ipfs-http-client README, not the core-api docs as they make no sense in the context of calling into core/running a full IPFS node in the browser or node.js

I added jsdoc comment but have not added it the README, because I don't think we want users to pass this option as it would disable streaming. It is only used by `ipfs.add` and even there user does not need to provide additional option, existing `progress` handler is used.

> 3. Ensure it doesn't cause a regression for ipfs/js-ipfs#3238

Verified

2020-10-07 21:24 UTC, Gozala commented
Had to reset on top of current master, otherwise github complained about non-clean merge even though I did merge master in 🤷‍♂️

2020-10-07 21:59 UTC, Gozala commented
merged #62 into this as there was some overlap between two

2020-10-12 15:06 UTC, achingbrain commented
Can you fix the conflicts please?  Then we should try to get this resolved.

2020-10-13 00:27 UTC, Gozala commented
So #62 has introduced @achingbrain/electron-fetch as a dependency, which is API incompatible with both node-fetch and native fetch 😭, more specifically native and a `node-fetch` `Response` implementations accept `Uint8Array`s for a body, but electron-fetch does not:

https://github.com/achingbrain/electron-fetch/blob/b6a8cb74b4f04837140044af3396e150a5ee2e8c/src/body.js#L24-L44

Which causes them to be treated as strings leading to incorrect behavior here:

https://github.com/ipfs/js-ipfs-utils/blob/8111a80b470108b7602d034f440129a224c9125e/src/http/fetch.node.js#L82-L99

Furthermore unlike node-fetch electron-fetch represents `response.body` in different representations from node-fetch, which creates more problems
https://github.com/node-fetch/node-fetch/blob/cbd4d895767e33491219e40013dd8daa5c7ac024/src/body.js#L35-L69

What's worth both seem to ignore that `response.body` supposed be `ReadableStream`.

2020-10-13 00:54 UTC, Gozala commented
@achingbrain I've update patch so that it overcomes issues mentioned in last comment. While it would make sense to make changes to electron-fetch to make it more API compatible with node-fetch, I would really really like to avoid blocking this further, and pursue that separately. This is already several degrees separated from the actual task of **having a progress bar when you import files in webui**.

2020-10-20 14:00 UTC, lidel approved these changes
As long, we have tests that guard against regressions (see comment inline), lgtm!

@achingbrain we need this to unblock improved import UX scheduled to land as part of pinning service integration:
- https://github.com/ipfs-shipyard/ipfs-webui/issues/1594
- https://github.com/ipfs-shipyard/ipfs-webui/pull/1655

2020-10-20 16:02 UTC, Gozala commented on test/http.spec.js
> +    await all(request.iterator())
Sure, I'll add that

2020-11-11 18:00 UTC, achingbrain requested changes

2020-11-11 18:00 UTC, achingbrain commented on test/http.spec.js
> +        expect(progress).to.have.property('loaded').to.be.greaterThan(0)
Minor nit, a bit more readable:

```suggestion
        expect(progress).to.have.property('loaded').that.is.greaterThan(0)
```

2020-11-13 07:19 UTC, Gozala commented on src/http/fetch.browser.js
> +  // it uses JSDOM which does not provide a global fetch
You told me in the earlier comment to:

> Ensure it doesn't cause a regression for ipfs/js-ipfs#3238

Which is why this done here.

2020-11-13 07:34 UTC, Gozala commented on test/http.spec.js
> +    await all(request.iterator())
Addressed

2020-11-13 08:09 UTC, Gozala commented
@achingbrain can you please let me know what else needs to be done here ?

2020-11-13 08:20 UTC, achingbrain approved these changes

2020-11-13 09:41 UTC, merged

2020-11-13 13:57 UTC, achingbrain commented
@hugomrdias could you eyeball these changes and release if you're happy with them please?

2020-11-16 08:07 UTC, hugomrdias commented
Sure I will do it asap.

Hugo Dias

On Fri, Nov 13, 2020, 13:57 Alex Potsides <notifications@github.com> wrote:

> @hugomrdias <https://github.com/hugomrdias> could you eyeball these
> changes and release if you're happy with them please?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ipfs/js-ipfs-utils/pull/60#issuecomment-726778881>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACMWTXHSN5J7WYNK2LN6GDSPU3OFANCNFSM4QCOMJPA>
> .
>